### ISSUE TITLE
dev branch installl broken?

### ISSUE THREAD

**Issue by AnotherSimon** [openvar/rest_variantValidator#30]
Hi Peter,

Ignoring a few special cases where variants caused VariantValidator to hang, I had the REST docker up and running. You recommended switching to the `develop branch with the following instructions:

```bash
$ git fetch
$ git checkout develop
$ git pull
```

However, after doing so, `docker-compose up` runs into problems:

```bash
root@testsrv:/home/..../rest_variantValidator# docker-compose up
Starting rest_variantvalidator_seqrepo_1 ... done
Starting rest_variantvalidator_uta_1     ... done
Starting rest_variantvalidator_vdb_1     ... done
Starting rest_variantvalidator_restvv_1  ... done
Attaching to rest_variantvalidator_uta_1, rest_variantvalidator_seqrepo_1, rest_variantvalidator_vdb_1, rest_variantvalidator_restvv_1
uta_1      | 
uta_1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
uta_1      | 
uta_1      | 2020-05-06 21:34:18.593 UTC [1] LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
uta_1      | 2020-05-06 21:34:18.593 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
uta_1      | 2020-05-06 21:34:18.593 UTC [1] LOG:  listening on IPv6 address "::", port 5432
uta_1      | 2020-05-06 21:34:18.626 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
uta_1      | 2020-05-06 21:34:18.670 UTC [25] LOG:  database system was shut down at 2020-05-06 21:34:10 UTC
uta_1      | 2020-05-06 21:34:18.699 UTC [1] LOG:  database system is ready to accept connections
vdb_1      | 2020-05-06 21:34:20+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.20-1debian10 started.
vdb_1      | 2020-05-06 21:34:20+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
vdb_1      | 2020-05-06 21:34:20+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.20-1debian10 started.
vdb_1      | 2020-05-06T21:34:21.147555Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
vdb_1      | 2020-05-06T21:34:21.147740Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.20) starting as process 1
vdb_1      | 2020-05-06T21:34:21.159991Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
vdb_1      | 2020-05-06T21:34:21.822875Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
vdb_1      | 2020-05-06T21:34:22.018637Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind-address: '::' port: 33060
vdb_1      | 2020-05-06T21:34:22.170969Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
vdb_1      | 2020-05-06T21:34:22.179394Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
vdb_1      | 2020-05-06T21:34:22.205768Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.20'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
restvv_1   | [2020-05-06 21:34:22 +0000] [6] [INFO] Starting gunicorn 20.0.4
restvv_1   | [2020-05-06 21:34:22 +0000] [6] [INFO] Listening at: http://0.0.0.0:8000 (6)
restvv_1   | [2020-05-06 21:34:22 +0000] [6] [INFO] Using worker: gthread
restvv_1   | [2020-05-06 21:34:22 +0000] [9] [INFO] Booting worker with pid: 9
restvv_1   | [2020-05-06 21:34:22 +0000] [9] [ERROR] Exception in worker process
restvv_1   | Traceback (most recent call last):
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
restvv_1   |     worker.init_process()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
restvv_1   |     super().init_process()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 119, in init_process
restvv_1   |     self.load_wsgi()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
restvv_1   |     self.wsgi = self.app.wsgi()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
restvv_1   |     self.callable = self.load()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
restvv_1   |     return self.load_wsgiapp()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
restvv_1   |     return util.import_app(self.app_uri)
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 358, in import_app
restvv_1   |     mod = importlib.import_module(module)
restvv_1   |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
restvv_1   |     return _bootstrap._gcd_import(name[level:], package, level)
restvv_1   |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
restvv_1   |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
restvv_1   |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
restvv_1   |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
restvv_1   |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
restvv_1   |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
restvv_1   |   File "/app/rest_VariantValidator/app.py", line 8, in <module>
restvv_1   |     from .endpoints import api, representations, exceptions, request_parser
restvv_1   | ImportError: attempted relative import with no known parent package
restvv_1   | [2020-05-06 21:34:22 +0000] [9] [INFO] Worker exiting (pid: 9)
restvv_1   | [2020-05-06 21:34:22 +0000] [6] [INFO] Shutting down: Master
restvv_1   | [2020-05-06 21:34:22 +0000] [6] [INFO] Reason: Worker failed to boot.
seqrepo_1  | WARNING:biocommons.seqrepo.cli:2018-08-21: instance already exists; skipping
rest_variantvalidator_seqrepo_1 exited with code 0
rest_variantvalidator_restvv_1 exited with code 3
^CGracefully stopping... (press Ctrl+C again to force)
Stopping rest_variantvalidator_vdb_1     ... done
Stopping rest_variantvalidator_uta_1     ... done
```

**Comment by PeteCausey-Freeman** [comment]
Hi Thanks.

I'll get this sorted

**Comment by PeteCausey-Freeman** [comment]
Note, I forgot to say that the reason I recommended the switch is that the version you are using is no longer maintained and will be deprecated in the very near future. I'm currently working withe the LOVD team to stress test our software and iron out bugs like the ones you saw. I have also had to change the framework for the API because a dependant software is no longer maintained. 

So you can get a feel for the updated API, the dev server is on https://www35.lamp.le.ac.uk/

**Comment by PeteCausey-Freeman** [comment]
Hi @AnotherSimon . I believe I have spotted the issue. A really annoying single letter typo. Testing now and if good I will push up. 

Also configured MySQL and Postgres to novel ports to try stop your conflict issues.

**Comment by PeteCausey-Freeman** [comment]
Hi @AnotherSimon 
Very sorry for the delay. I have been fighting this for days and finally managed to identify an issue burried inside one of the dependancies. FACE-PALM

Anyway, I have tweaked the installation process, fixed the issue, and for something that might be really interesting to you, I have also included documentation and additional functionality that gives you a complete install of VV and all the tools that can be run on the command-line within the docker container. 

I'm just completing the documentation and applying a few additional tweaks then will let you know so I can get some feedback if thats OK?

**Comment by AnotherSimon** [comment]
Neat. Looking forward to the update.

Out of curiosity, could a user decide to start off with the docker install and then update parts of the pipeline, for example update the SeqRepo version in the container, without breaking anything? (anything can be broken but you get the idea)

**Comment by PeteCausey-Freeman** [comment]
Great shout mate, 

The list of available seqrepo databases is here. http://dl.biocommons.org/seqrepo/

Tell you what, I will build a docker container with a more up-to-date SeqRepo build and see if it still runs then provide feedback on what I did. I will add to docs too.

Basically, based on your feedback I'm trying to make this docker container a customisable distributed version of the whole VariantValidator tool set for internal use.

**Comment by AnotherSimon** [comment]
Any updates on getting a working version of the REST docker uploaded?

**Comment by PeteCausey-Freeman** [comment]
Hi mate,

sorry for the delay. I was almost done but had to drop everything to write an urgent grant. I forgot to let you know. I'll be back on it in a couple days. I need to figure out 1 more thing then we are good to go.

Hope you are well

**Comment by PeteCausey-Freeman** [comment]
OK, try now.

I have added instructions to use VV as an installed version of the commandline tool. May need to improve documentation to access the data outside the container though but feedback so far would be appreciated. 

I'm going to try get hold of a docker expert to add additional documentation. Think this is looking like quite an exciting package now though. Thanks for your development ideas @AnotherSimon

**Comment by AnotherSimon** [comment]
Thanks for the update Peter. Had to finish something else up before I could get to this project.

First tests indicate it's running nominally. Haven't had time to mess around inside the new containers but once the first batch of variants has been processed I'll give it a go and provide some feedback.

**Comment by AnotherSimon** [comment]
Most of the errors I am encountering right now seem to be of the category `Interval length measured from different datums is ill-defined`. The output from my wrapper script:

```
Warning: Skipping variant chr3:52436301:TCCTC:T due to validation error.
Warning: Skipping variant chr19:4090593:CTGT:C due to validation error.
Warning: Skipping variant chr22:41574941:GTACACTAGACA:G due to validation error.
Warning: Skipping variant chr19:13054723:TGTAGAGAGGC:T due to validation error.
Warning: Skipping variant chr6:26046048:AAGTC:A due to validation error.
Warning: Skipping variant chr19:1226642:AGTGAGG:A due to validation error.
Warning: Skipping variant chr3:52436301:TCCTC:T due to validation error.
Warning: Skipping variant chr19:13054723:TGTAGAGAGGC:T due to validation error.

{'flag': 'warning', 'metadata': {'seqrepo_db': '2018-08-21', 'uta_schema': 'uta_20180821', 'variantvalidator_hgvs_version': '1.2.5.vv1', 'variantvalidator_version': '1.0.4.dev65+g514626a'}}
```

(all hg19)

**Comment by PeteCausey-Freeman** [comment]
Brilliant. I will take a look at these thanks. This is likely a VV issue rather than the API so transferring
