### ISSUE TITLE
restvv_1 fails to boot workers

### ISSUE THREAD

**Issue by AnotherSimon** [openvar/rest_variantValidator#39]
Good to see some new updates to this repo! Unfortunately I have to be a bearer of bug news (for build 86d0acc) :

```
root@xxxx:~/rest_variantValidator# docker-compose up
Creating network "rest_variantvalidator_default" with the default driver
Creating rest_variantvalidator_uta_1     ... done
Creating rest_variantvalidator_seqrepo_1 ... done
Creating rest_variantvalidator_vdb_1     ... done
Creating rest_variantvalidator_restvv_1  ... done
Attaching to rest_variantvalidator_seqrepo_1, rest_variantvalidator_vdb_1, rest_variantvalidator_uta_1, rest_variantvalidator_restvv_1
restvv_1   | [2020-10-28 15:14:17 +0000] [6] [INFO] Starting gunicorn 20.0.4
restvv_1   | [2020-10-28 15:14:17 +0000] [6] [INFO] Listening at: http://0.0.0.0:8000 (6)
restvv_1   | [2020-10-28 15:14:17 +0000] [6] [INFO] Using worker: threads
restvv_1   | [2020-10-28 15:14:17 +0000] [9] [INFO] Booting worker with pid: 9
restvv_1   | [2020-10-28 15:14:17 +0000] [11] [INFO] Booting worker with pid: 11
restvv_1   | [2020-10-28 15:14:17 +0000] [12] [INFO] Booting worker with pid: 12
restvv_1   | Exception ignored in: <bound method Mixin.__del__ of <VariantValidator.validator.Validator object at 0x7f2b703c9cf8>>
restvv_1   | Traceback (most recent call last):
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/VariantValidator/modules/vvMixinInit.py", line 191, in __del__
restvv_1   |     del self.db
restvv_1   | AttributeError: db
restvv_1   | Exception ignored in: <bound method Mixin.__del__ of <VariantValidator.validator.Validator object at 0x7f2b703f9be0>>
restvv_1   | Traceback (most recent call last):
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/VariantValidator/modules/vvMixinInit.py", line 191, in __del__
restvv_1   |     del self.db
restvv_1   | AttributeError: db
restvv_1   | Exception ignored in: <bound method Mixin.__del__ of <VariantValidator.validator.Validator object at 0x7f2b703fac50>>
restvv_1   | Traceback (most recent call last):
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/VariantValidator/modules/vvMixinInit.py", line 191, in __del__
restvv_1   |     del self.db
restvv_1   | AttributeError: db
restvv_1   | Traceback (most recent call last):
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 209, in run
restvv_1   |     self.sleep()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 357, in sleep
restvv_1   |     ready = select.select([self.PIPE[0]], [], [], 1.0)
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
restvv_1   |     self.reap_workers()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
restvv_1   |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
restvv_1   | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
restvv_1   | 
restvv_1   | During handling of the above exception, another exception occurred:
restvv_1   | 
restvv_1   | Traceback (most recent call last):
restvv_1   |   File "/usr/local/bin/gunicorn", line 8, in <module>
restvv_1   |     sys.exit(run())
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
restvv_1   |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 228, in run
restvv_1   |     super().run()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
restvv_1   |     Arbiter(self).run()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 229, in run
restvv_1   |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 342, in halt
restvv_1   |     self.stop()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
restvv_1   |     time.sleep(0.1)
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
restvv_1   |     self.reap_workers()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
restvv_1   |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
restvv_1   | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
rest_variantvalidator_restvv_1 exited with code 1

```

**Comment by PeteCausey-Freeman** [comment]
Hi @AnotherSimon 
Thanks for the update. We are currently in the process of pushing a major new database release. I'll see if I can replicate this current issue at my end and fix the current master build. I think I may know what went wrong.

**Comment by PeteCausey-Freeman** [comment]
Thought as much. I forgot to specify the Docker entrypoint for the new database location. Try again. Should be fixed. Don't forget to git pull.

**Comment by PeteCausey-Freeman** [comment]
Also, would you be willing to drop us an email. You are becoming a regular user. Would be nice to know a little more about you. This isn't the place! Haha

https://variantvalidator.org/help/contact/

**Comment by AnotherSimon** [comment]
f090437 still gives me a similar error:
```
restvv_1   | [2020-10-28 17:37:44 +0000] [6] [INFO] Starting gunicorn 20.0.4
restvv_1   | [2020-10-28 17:37:44 +0000] [6] [INFO] Listening at: http://0.0.0.0:8000 (6)
restvv_1   | [2020-10-28 17:37:44 +0000] [6] [INFO] Using worker: threads
restvv_1   | [2020-10-28 17:37:44 +0000] [9] [INFO] Booting worker with pid: 9
restvv_1   | [2020-10-28 17:37:44 +0000] [10] [INFO] Booting worker with pid: 10
restvv_1   | [2020-10-28 17:37:44 +0000] [12] [INFO] Booting worker with pid: 12
restvv_1   | Exception ignored in: <bound method Mixin.__del__ of <VariantValidator.validator.Validator object at 0x7fa798809c88>>
restvv_1   | Traceback (most recent call last):
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/VariantValidator/modules/vvMixinInit.py", line 191, in __del__
restvv_1   |     del self.db
restvv_1   | AttributeError: db
restvv_1   | Exception ignored in: <bound method Mixin.__del__ of <VariantValidator.validator.Validator object at 0x7fa79883bbe0>>
restvv_1   | Traceback (most recent call last):
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/VariantValidator/modules/vvMixinInit.py", line 191, in __del__
restvv_1   |     del self.db
restvv_1   | AttributeError: db
restvv_1   | Exception ignored in: <bound method Mixin.__del__ of <VariantValidator.validator.Validator object at 0x7fa79883ab70>>
restvv_1   | Traceback (most recent call last):
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/VariantValidator/modules/vvMixinInit.py", line 191, in __del__
restvv_1   |     del self.db
restvv_1   | AttributeError: db
restvv_1   | Traceback (most recent call last):
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 209, in run
restvv_1   |     self.sleep()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 357, in sleep
restvv_1   |     ready = select.select([self.PIPE[0]], [], [], 1.0)
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
restvv_1   |     self.reap_workers()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
restvv_1   |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
restvv_1   | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
restvv_1   | 
restvv_1   | During handling of the above exception, another exception occurred:
restvv_1   | 
restvv_1   | Traceback (most recent call last):
restvv_1   |   File "/usr/local/bin/gunicorn", line 8, in <module>
restvv_1   |     sys.exit(run())
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
restvv_1   |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 228, in run
restvv_1   |     super().run()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
restvv_1   |     Arbiter(self).run()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 229, in run
restvv_1   |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 342, in halt
restvv_1   |     self.stop()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
restvv_1   |     time.sleep(0.1)
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
restvv_1   |     self.reap_workers()
restvv_1   |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
restvv_1   |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
restvv_1   | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
rest_variantvalidator_restvv_1 exited with code 1

```

**Comment by PeteCausey-Freeman** [comment]
HMM. OK, I'll dig a little deeper. Thanks

**Comment by PeteCausey-Freeman** [comment]
Hi mate,
in the vdb_docker.df file, try replacing the wget statement with
`RUN wget https://github.com/openvar/VV_databases/raw/master/validator/validator_2020-10-01.sql -O /docker-entrypoint-initdb.d/validator_2020-10-01.sql`

**Comment by PeteCausey-Freeman** [comment]
It looks like Mysql is failing to load. I think Ive seen this before

**Comment by AnotherSimon** [comment]
Edited in that line manually but still no luck. I do seem to remember a similar error message about gunicorn and workers not booting (see #30). Also included vdb output below (rest_vv output is the same as above). And there does seem to be an outdated URL for mysql repo (see end of this post).
```
vdb_1      | 2020-10-29 08:49:22+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
vdb_1      | 2020-10-29 08:49:22+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
vdb_1      | 2020-10-29 08:49:22+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
vdb_1      | 2020-10-29 08:49:22+00:00 [Note] [Entrypoint]: Initializing database files
vdb_1      | 2020-10-29T08:49:22.757236Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.22) initializing of server in progress as process 44
vdb_1      | 2020-10-29T08:49:22.762098Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
vdb_1      | 2020-10-29T08:49:23.258327Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
vdb_1      | 2020-10-29T08:49:24.449407Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
vdb_1      | 2020-10-29 08:49:27+00:00 [Note] [Entrypoint]: Database files initialized
vdb_1      | 2020-10-29 08:49:27+00:00 [Note] [Entrypoint]: Starting temporary server
vdb_1      | 2020-10-29T08:49:27.892526Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.22) starting as process 89
vdb_1      | 2020-10-29T08:49:27.907796Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
vdb_1      | 2020-10-29T08:49:28.092885Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
vdb_1      | 2020-10-29T08:49:28.168663Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
vdb_1      | 2020-10-29T08:49:28.239873Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
vdb_1      | 2020-10-29T08:49:28.240075Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
vdb_1      | 2020-10-29T08:49:28.242486Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
vdb_1      | 2020-10-29T08:49:28.255031Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.22'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
vdb_1      | 2020-10-29 08:49:28+00:00 [Note] [Entrypoint]: Temporary server started.
vdb_1      | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
vdb_1      | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
vdb_1      | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
vdb_1      | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
vdb_1      | 2020-10-29 08:49:30+00:00 [Note] [Entrypoint]: GENERATED ROOT PASSWORD: ahth1ieMa5yi1faic7yeeth2ahPhu6Oo
vdb_1      | 2020-10-29 08:49:30+00:00 [Note] [Entrypoint]: Creating database validator
vdb_1      | 2020-10-29 08:49:30+00:00 [Note] [Entrypoint]: Creating user vvadmin
vdb_1      | 2020-10-29 08:49:30+00:00 [Note] [Entrypoint]: Giving user vvadmin access to schema validator
vdb_1      | 
vdb_1      | 2020-10-29 08:49:30+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/validator_2020-10-01.sql
vdb_1      | 
vdb_1      | 
vdb_1      | 2020-10-29 08:49:34+00:00 [Note] [Entrypoint]: Stopping temporary server
vdb_1      | 2020-10-29T08:49:34.740473Z 14 [System] [MY-013172] [Server] Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.22).
vdb_1      | 2020-10-29T08:49:36.359823Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.22)  MySQL Community Server - GPL.
vdb_1      | 2020-10-29 08:49:36+00:00 [Note] [Entrypoint]: Temporary server stopped
vdb_1      | 
vdb_1      | 2020-10-29 08:49:36+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
vdb_1      | 
vdb_1      | 2020-10-29T08:49:36.970342Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.22) starting as process 1
vdb_1      | 2020-10-29T08:49:36.976988Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
vdb_1      | 2020-10-29T08:49:37.208580Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
vdb_1      | 2020-10-29T08:49:37.317249Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
vdb_1      | 2020-10-29T08:49:37.421916Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
vdb_1      | 2020-10-29T08:49:37.422056Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
vdb_1      | 2020-10-29T08:49:37.424370Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
vdb_1      | 2020-10-29T08:49:37.442712Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.22'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
```
On a side note, earlier in the docker-compose build step:
```
Get:7 http://deb.debian.org/debian buster-updates/main amd64 Packages [7856 B]
Err:3 http://repo.mysql.com/apt/debian buster InRelease
  Connection timed out [IP: XXX.XXX.XXX.XXX XXX]
Fetched 8396 kB in 30s (279 kB/s)
Reading package lists...
W: Failed to fetch http://repo.mysql.com/apt/debian/dists/buster/InRelease  Connection timed out [IP: 10.21.4.153 1234]
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
...
debconf: delaying package configuration, since apt-utils is not installed
...
```

**Comment by PeteCausey-Freeman** [comment]
Thanks for hints. I have a bit more time today. I'll take a look. I think something may have become over-written in the merging of several branches. On it

**Comment by PeteCausey-Freeman** [comment]
As for the pull issue. This is a new docker enforced thing. I got an email late last night. I will invstigate

**Comment by PeteCausey-Freeman** [comment]
Hi @AnotherSimon 

I have pushed a revised version

https://github.com/openvar/rest_variantValidator/commit/43e2b8aa76ca4e4e9202182070ac118261a87cdb

Note, the warning `rest_variantvalidator_seqrepo_1 exited with code 0` does not mean a failure. It seems to be happening because seqrepo is already running. I think the container is a little odd!!!

I have made a not of this in the docker manual.

Closing this for now, but feel free to reopen if you need to
