### ISSUE TITLE
flask requirement not installable + fix?

### ISSUE THREAD

**Issue by AnotherSimon** [openvar/rest_variantValidator#44]
While installing build 'f090437' I hit the following snag:

```
$ python setup.py install
running install
running bdist_egg
...
Searching for flask-restplus
Reading https://pypi.org/simple/flask-restplus/
Downloading https://files.pythonhosted.org/packages/c2/a6/b17c848771f96ad039ad9e3ea275e842a16c39c4f3eb9f60ee330b20b6c2/flask_restplus-0.13.0-py2.py3-none-any.whl#sha256=a15d251923a8feb09a5d805c2f4d188555910a42c64d58f7dd281b8cac095f1b
Best match: flask-restplus 0.13.0
Processing flask_restplus-0.13.0-py2.py3-none-any.whl
Installing flask_restplus-0.13.0-py2.py3-none-any.whl to /root/variantValidator/vvenv/lib/python3.8/site-packages
Adding flask-restplus 0.13.0 to easy-install.pth file

Installed XXX/variantValidator/vvenv/lib/python3.8/site-packages/flask_restplus-0.13.0-py3.8.egg
Searching for flask
Downloading https://files.pythonhosted.org/packages/ac/d6/270f22ed9974e3ce0a3cc8c0be08211e63f82b46550dda85d0ae26b37371/flask-restplus-0.13.0.tar.gz#sha256=a66e442d0bca08f389fc3d07b4d808fc89961285d12fb8013f7cf15516fa9f5c
Best match: flask restplus-0.13.0
Processing flask-restplus-0.13.0.tar.gz
Writing /tmp/easy_install-dpp61r9m/flask-restplus-0.13.0/setup.cfg
Running flask-restplus-0.13.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-dpp61r9m/flask-restplus-0.13.0/egg-dist-tmp-r2mghkbe
/usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'dev_require'
  warnings.warn(msg)
warning: no previously-included files matching '*.pyc' found anywhere in distribution
removing 'XXX/variantValidator/vvenv/lib/python3.8/site-packages/flask_restplus-0.13.0-py3.8.egg' (and everything under it)
creating XXX/variantValidator/vvenv/lib/python3.8/site-packages/flask_restplus-0.13.0-py3.8.egg
Extracting flask_restplus-0.13.0-py3.8.egg to XXX/variantValidator/vvenv/lib/python3.8/site-packages
flask-restplus 0.13.0 is already the active version in easy-install.pth

Installed XXX/variantValidator/vvenv/lib/python3.8/site-packages/flask_restplus-0.13.0-py3.8.egg
error: The 'flask' distribution was not found and is required by rest-VariantValidator
```

Commenting out flask (but leaving flask-restplus) in `REQUIREMENTS.TXT` seems to do the trick.
However, this does lead to a new issue:
```
(vvenv) XXX@XXX:~/rest_variantValidator# python ./wsgi.py
Traceback (most recent call last):
  File "./wsgi.py", line 4, in <module>
    from rest_VariantValidator.app import application as application
  File "XXX/rest_variantValidator/rest_VariantValidator/app.py", line 7, in <module>
    from rest_VariantValidator.endpoints import api, representations, exceptions, request_parser
  File "XXX/rest_variantValidator/rest_VariantValidator/endpoints/__init__.py", line 4, in <module>
    from flask_restplus import Api
  File "XXX/variantValidator/vvenv/lib/python3.8/site-packages/flask_restplus-0.13.0-py3.8.egg/flask_restplus/__init__.py", line 4, in <module>
    from . import fields, reqparse, apidoc, inputs, cors
  File "XXX/variantValidator/vvenv/lib/python3.8/site-packages/flask_restplus-0.13.0-py3.8.egg/flask_restplus/fields.py", line 17, in <module>
    from werkzeug import cached_property
ImportError: cannot import name 'cached_property' from 'werkzeug' (XXX/variantValidator/vvenv/lib/python3.8/site-packages/Werkzeug-1.0.1-py3.8.egg/werkzeug/__init__.py)
```
Further, this could just be a bit of confusion about the path in the manual but there is no `~/rest_variantValidator/rest_variantValidator/wsgi.py` for me (only `~/rest_variantValidator/wsgi.py`).

**Comment by PeteCausey-Freeman** [comment]
Hi @AnotherSimon 

I am tweaking the INSTALLATION.md.

To be clear, are you installing locally????

**Comment by AnotherSimon** [comment]
yup, local install (no docker), VV itself is up and running in this virtual environment

**Comment by PeteCausey-Freeman** [comment]
OK,

I am updating the workflow.

below is what I will be adding. It works for me, but perhaps see i it works for you before I commit

**Comment by PeteCausey-Freeman** [comment]
# Installation

These instructions will allow you to install the package and accompanying databases on Linux. Mac OS X computers operate similarly.
For any other systems, or if you cannot install the databases, we recommend installing via [docker](DOCKER.md).

## Pre-requisites
Installation requires [VariantValidator](https://github.com/openvar/variantValidator) and [VariantFormatter](https://github.com/openvar/variantFormatter)

## Installing VariantValidator

When installing  we have found that some of the VariantValidator dependencies do not load well using pip.
Instead install VariantValidator first using anaconda and the pre-configured environment.yml 
See the [VariantValidator](https://github.com/openvar/variantValidator) installation documentation

## Download the source code

To download the source code simply clone the master branch.

```
$ git clone https://github.com/openvar/rest_variantValidator
$ cd rest_variantValidator
```

## Installing rest_variantValidator

To install rest_variantValidator within your virtual environment, activate the environment and run:
```
$ pip install -e .
```

**Comment by PeteCausey-Freeman** [comment]
Note, make sure you build VariantValidator first using anaconda if possible. PySam is very unstable when installed via pip

**Comment by PeteCausey-Freeman** [comment]
# Manual

## Operation

To run rest_variantValidator

### In dev mode upsing Python

```bash
$ python wsgi.py
```

You will be provided with a link which will open rest_variantValidator in your web browser. [http://127.0.0.1:5000/](http://127.0.0.1:5000/)


## Swagger documented functions
The rest_variantValidator functions have swagger documentation to help you generate URLs to make direct API calls utilising human readable text-input boxes. 

Once the documented page opens in your web-browser, click the variantvalidator link and the documented functions will appear. 

A web-hosted version of this rest API can be found at [https://rest.variantvalidator.org](https://rest.variantvalidator.org)  

## Direct request
Direct URL calls can be made to the rest-API. The easiest way to create these URLs is to use the swagger documented functions

## In a Docker container

## Apache web-server and mod_wsgi
Mounting rest_variantValidator to an Apache web server requires [mod_wsgi](https://pypi.org/project/mod-wsgi/)

Example [Apache configuration](https://modwsgi.readthedocs.io/en/develop/user-guides/quick-configuration-guide.html)

***Note: you will need to configure the file paths in the example below***

```apacheconf
<IfModule wsgi_module>

	WSGIPythonPath /local/miniconda3/envs/vvenv/lib:/local/miniconda3/envs/vvenv/lib/python3.6/site-packages
	WSGIDaemonProcess rest_variantValidator user=wwwrun group=www threads=5
	WSGIScriptAlias / /local/py3Repos/rest_variantValidator/wsgi.py
	WSGIPythonHome /local/miniconda3/envs/vvenv
    	    	
    	<Directory /local/py3Repos/rest_variantValidator/>
        	WSGIProcessGroup rest_variantValidator
         	WSGIApplicationGroup %{GLOBAL}
            Order allow,deny
            Allow from all
            Header set Access-Control-Allow-Origin "*"
            Header set Access-Control-Allow-Methods "GET"
     	</Directory>

</IfModule>
LogLevel crit
CustomLog /local/apache2/log/access_log for_pound


```

## Additional resources
We are compiling a number of jupyter notebook user guides for rest_variantValidator in [rest_variantValidator_manuals](https://github.com/openvar/rest_variantValidator_manuals)

**Comment by PeteCausey-Freeman** [comment]
Let me know if these changes help

**Comment by AnotherSimon** [comment]
I did indeed create the VarVal virt env with native python rather than anaconda but can't confirm that that was definitely the problem.

After flask issues were sorted out I had to fix one more bug with werkzeug (wrong version installed) by going into the environment, `pip uninstall werkzeug` and then `pip install werkzeug==0.16.1`. I suspect that because the requirements.txt file in VariantValidator do not specify (a specific version of) Werkzeug, it just went with the most recent one because it was considered a dependency for some other package in the chain of installs.

Updates to the documentation look fine, can't think of anything I would do differently at this time.

**Comment by AnotherSimon** [comment]
On a somewhat related note, should I be concerned about this warning from `wsgi.py`?
```
python ./wsgi.py 
 * Serving Flask app "rest_VariantValidator.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.

```

**Comment by PeteCausey-Freeman** [comment]
Noted r.e. the setup.py file thanks. Updating now.

I think I remember the issue. There was an issue with Flask or Flask Restplus and newer versions of WerkZeug that seemed to cause a bug.

Here is the setup.py now

```python
    # List run-time dependencies here.  These will be installed by pip when the project is installed.
    install_requires=[
        "werkzeug==0.16.1"
        "flask",
        "flask-restplus",
        "gunicorn",
        "httplib2>=0.9.0",
        "configparser>=3.5.0",
        "pyliftover>=0.3",
        "biotools>=0.3.0",
        "mysql-connector-python",
        "requests",
        "dicttoxml",
        "vvhgvs @ git+https://github.com/openvar/vv_hgvs.git@1.2.5.vv1#egg=vvhgvs",
        "VariantValidator @ git+https://github.com/openvar/variantValidator.git@master#egg=VariantValidator",
        "VariantFormatter @ git+https://github.com/openvar/variantFormatter.git@master#egg=VariantFormatter",
        "biocommons.seqrepo>=0.5.1",
    ],
    setup_requires=[
        "setuptools_scm",
    ]
```
I have put Werkzeug aboove Flask. The werkzeug==0.16.1 is specified in the requirements.txt but I have moved it above flask.

May I ask exactly what the issue was with installing Flask? I wonder if I should specify a version.

**Comment by PeteCausey-Freeman** [comment]
Don't be alarmed by the wsgi waning. This is just telling you that if you intend to put the app onto a web server, you should be using Apache or something else as the server, not running the development server by Python(ing) the file. Hence the demo Apache config.

**Comment by AnotherSimon** [comment]
So with the use case I emailed you recently in mind, do you recommend that I should run my instance on apache?

**Comment by PeteCausey-Freeman** [comment]
If the tool is just being run on, and accessed on, a single machine I see no reason to go to the hassle of setting up apache. If you are setting up an internal API that you and colleagues are accessing via web, I think Apache might be the way to go. I wouldn't bother setting up Apache unless you really need to. It can be a hassle!!!!

**Comment by PeteCausey-Freeman** [comment]
Hi @AnotherSimon 
I am having to migrate onto new servers so will be updating all the installation manuals needed to install VV and VariantFormatter and the API.

I will test, and post the updated versions here for your comments before committing. Is that OK?

**Comment by AnotherSimon** [comment]
I've made decent progress in setting up apache2 and mod_wsgi. I did notice that wsgi.py explicitely points to port 5000. Does this mean I should also change my virtualhost config file to be bound to port 5000? Or can I just change that value in wsgi.py?

**Comment by PeteCausey-Freeman** [comment]
If you look in the wsgi.py

The tool is only pointed at :5000 if you run the script directly. i.e. if __name__ == '__main__':

So the :5000 will be ignored by the Apache installation. If you get stuck at any point we can set up a zoom call to go through my progress. I'm currently building too.

```python
if __name__ == '__main__':
    from configparser import ConfigParser
    from VariantValidator.settings import CONFIG_DIR
    config = ConfigParser()
    config.read(CONFIG_DIR)
    if config["logging"]["log"] == "True":
        application.debug = True
        application.config['PROPAGATE_EXCEPTIONS'] = True
    else:
        application.debug = False
        application.config['PROPAGATE_EXCEPTIONS'] = False
    application.run(host="127.0.0.1", port=5000)
```

On thing you will need to identify is the location of the home directory used by Apache. VV will copy a config file here and you will need to edit it. Again, if needed let's set up a call. I'll also need to add this to the documentation so we can work on the wording

**Comment by PeteCausey-Freeman** [comment]
As for the error, did you manage to install rest_vv into your virtual environment?

is might be worth posting your Apache config so I can take a look.

**Comment by AnotherSimon** [comment]
I figured out the cause of my error. I created a `wwwrun` user following your template for the WSGI config. First I needed to check that that this user could run rest_VV interactively in the virtual environment.

While addressing this, I noticed an interesting artefact. The base directory for the virtual environment is a sub-folder of my variantValidator folder. But if I want to be able to run the python command `from rest_VariantValidator.app import application as application`, this only work if I first `cd` to the rest_variantValidator folder (with vvenv active). To achieve something similar for apache I had to change my WSGI config to the following:
```
    WSGIDaemonProcess rest_variantValidator user=wwwrun group=www threads=5 home=/srv/rest_variantValidator python-home=/srv/variantValidator/vvenv
    WSGIProcessGroup rest_variantValidator

    WSGIScriptAlias / /srv/rest_variantValidator/wsgi.py

        <Directory /srv/rest_variantValidator/>
            WSGIProcessGroup rest_variantValidator
            WSGIApplicationGroup %{GLOBAL}
            Require all granted
#            Header set Access-Control-Allow-Origin "*"
#            Header set Access-Control-Allow-Methods "GET"
        </Directory>
```
The header options are not valid for apache 2.4 and [guidelines](https://modwsgi.readthedocs.io/en/develop/user-guides/virtual-environments.html#adding-additional-module-directories) on how to use [WSGIDaemonProcess](https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIDaemonProcess.html) have also been updated.

**Comment by PeteCausey-Freeman** [comment]
Thanks for sharing this. 

This my apache config is taken from the live server (current) but I am having to migrate 4 servers now. 2 dev and 2 live. This is useful to know as I believe that the Apache version will have been upgraded. If as we both keep going we can make notes here and I will update the installation manuals with the information we gather.
