### ISSUE TITLE
restvv build fails to install pytest_cov dependency

### ISSUE THREAD

**Issue by squid-dev** [openvar/rest_variantValidator#45]
This is the error I'm getting:

> Downloading pytest-cov-1.1.tar.gz (7.0 kB)
>   Downloading pytest-cov-1.0.tar.gz (6.9 kB)
>   Downloading pytest-cov-0.15.tar.gz (12 kB)
>   Downloading pytest-cov-0.14.tar.gz (12 kB)
>   Downloading pytest-cov-0.13.tar.gz (12 kB)
>   Downloading pytest-cov-0.12.tar.gz (12 kB)
>     ERROR: Command errored out with exit status 1:
>      command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bjm4od9b/pytest-cov_03a35a85509d46f99aa5bfe9d7c39c02/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bjm4od9b/pytest-cov_03a35a85509d46f99aa5bfe9d7c39c02/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rjh47xki
>          cwd: /tmp/pip-install-bjm4od9b/pytest-cov_03a35a85509d46f99aa5bfe9d7c39c02/
>     Complete output (7 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-bjm4od9b/pytest-cov_03a35a85509d46f99aa5bfe9d7c39c02/setup.py", line 1, in <module>
>         import pytest_cov
>       File "/tmp/pip-install-bjm4od9b/pytest-cov_03a35a85509d46f99aa5bfe9d7c39c02/pytest_cov.py", line 202, in <module>
>         import coverage
>     ModuleNotFoundError: No module named 'coverage'
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
> ERROR: Service 'restvv' failed to build : The command '/bin/sh -c pip install -r REQUIREMENTS.txt' returned a non-zero code: 1

I can actually get by this error by setting a min version for pytest_cov in REQUIREMENTS.txt. But the build is taking forever as it's now going through dozens of versions of pytest.

The strange thing is that I didn't encounter this issue last time I built this, a few months ago, but now I'm having the problem on two different machines, my macOS dev box and the Linux server I'm deploying this to. It's almost as if the problem is with the pip repo.

Thanks!

**Comment by squid-dev** [comment]
I think I see now, the Dockerfile always upgrades pip to the latest, and there are issues with the resolver in pip 20.3, which was released a few weeks ago. I can get around the problem now by adding the following option in the Dockerfile:
`# Install any needed packages specified in requirements.txt
RUN pip install -r REQUIREMENTS.txt --use-deprecated=legacy-resolver`
[Related issue](https://github.com/pypa/pip/issues/9180)
